# Generated by Django 2.2 on 2021-07-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wizard',
            new_name='usuarios',
        ),
    ]
