# Generated by Django 2.2 on 2021-07-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210727_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='first_nmae',
            new_name='first_name',
        ),
    ]
